---
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000
    ports:
      - 8082:80
    volumes:
      - /home/ganesh:/srv
      - /Homelab/Files/AppData/Config/file-browser/database/filebrowser.db:/database.db 
      # Path to the database file use the touch command to crearte the file if it does not exist befrore starting the container
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
