version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 443:8082
    volumes:
      - /home/ganesh/:/data
      - /Homelab/Files/AppData/Config/file-browser:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
